[application]

# App (Project) Name
name = "dioxus_playground"
out_dir = "docs"

[web.app]

# HTML title tag content
title = "dioxus_playground"
base_path = "https://skutcher.github.io/dioxus_playground/"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
